countries = {
	'Thailand': {'sea': True, 
				'schengen': False, 
				'average_temperature': 30, 
				'currency_rate': 1.8,
				'the_rate_per_day' : 90},
	'Hungary': {'sea': False, 
				'schengen': True, 
				'average_temperature': 10, 
				'currency_rate': 0.3,
				'the_rate_per_day' : 15},
	'Germany': {'sea': True, 
				'schengen': True, 
				'average_temperature': 5, 
				'currency_rate': 80,
				'the_rate_per_day' : 4000},
	'Japan': {'sea': True, 
				'schengen': False, 
				'average_temperature': 15, 
				'currency_rate': 0.61,	
				'the_rate_per_day' : 31},
	'China': {'sea': True, 
				'schengen': False, 
				'average_temperature': 20, 
				'currency_rate': 9.67,
				'the_rate_per_day' : 484},
	'USA': {'sea': True, 
				'schengen': False, 
				'average_temperature': 18, 
				'currency_rate': 65.84,
				'the_rate_per_day' : 3292},
	'Switzerland': {'sea': False, 
				'schengen': False, 
				'average_temperature': 20, 
				'currency_rate': 66.17,	
				'the_rate_per_day' : 3292},
	'Brazil': {'sea': True, 
				'schengen': False, 
				'average_temperature': 25, 
				'currency_rate': 19.25,
				'the_rate_per_day' : 964},
	'Australia' : {'sea': True, 
				'schengen': False, 
				'average_temperature': 30, 
				'currency_rate': 49.96,
				'the_rate_per_day' : 2500},
				
	}